
package com.mycompany.arreglo_de_carros;


    public class Carros extends javax.swing.JFrame {

    public int aux, num_carros;
    public String ordenamiento;
    public int [] orden = new int[10000];
    public Clase_Carros array_carros[] = new Clase_Carros[1000];
    public Carros() {
        initComponents();
        
        Color.setVisible(false);
        Marca.setVisible(false);
        Kilometraje.setVisible(false);
        Modelo.setVisible(false);
        Color_text.setVisible(false);
        Marca_text.setVisible(false);
        Kilometraje_text.setVisible(false);
        Modelo_text.setVisible(false);
        Submit_Atributos.setVisible(false);
        Submit_cant.setVisible(false);
        numero_carros.setVisible(false);
        num_carros_text.setVisible(false);
        Text_area.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        numero_carros = new javax.swing.JTextField();
        Submit_cant = new javax.swing.JButton();
        num_carros_text = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        Marca_text = new javax.swing.JLabel();
        Modelo = new javax.swing.JTextField();
        Color = new javax.swing.JTextField();
        Kilometraje = new javax.swing.JTextField();
        Modelo_text = new javax.swing.JLabel();
        Color_text = new javax.swing.JLabel();
        Kilometraje_text = new javax.swing.JLabel();
        Submit_Atributos = new javax.swing.JButton();
        Ordenamiento_km = new javax.swing.JButton();
        Ordenamiento_md = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Text_area = new javax.swing.JTextArea();
        Ord_txt = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        numero_carros.setBackground(new java.awt.Color(204, 204, 204));
        numero_carros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_carrosActionPerformed(evt);
            }
        });

        Submit_cant.setBackground(new java.awt.Color(153, 153, 153));
        Submit_cant.setText("Submit");
        Submit_cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_cantActionPerformed(evt);
            }
        });

        num_carros_text.setText("# de carros:");

        Marca.setBackground(new java.awt.Color(204, 204, 204));
        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });

        Marca_text.setText("Marca");

        Modelo.setBackground(new java.awt.Color(204, 204, 204));
        Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloActionPerformed(evt);
            }
        });

        Color.setBackground(new java.awt.Color(204, 204, 204));

        Kilometraje.setBackground(new java.awt.Color(204, 204, 204));
        Kilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KilometrajeActionPerformed(evt);
            }
        });

        Modelo_text.setText("Modelo");

        Color_text.setText("Color");

        Kilometraje_text.setText(" Kilometraje");

        Submit_Atributos.setBackground(new java.awt.Color(153, 153, 153));
        Submit_Atributos.setText("Submit");
        Submit_Atributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_AtributosActionPerformed(evt);
            }
        });

        Ordenamiento_km.setBackground(new java.awt.Color(204, 204, 204));
        Ordenamiento_km.setText("Kilometraje");
        Ordenamiento_km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ordenamiento_kmActionPerformed(evt);
            }
        });

        Ordenamiento_md.setBackground(new java.awt.Color(204, 204, 204));
        Ordenamiento_md.setText("Modelo");
        Ordenamiento_md.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ordenamiento_mdActionPerformed(evt);
            }
        });

        Text_area.setBackground(new java.awt.Color(204, 204, 204));
        Text_area.setColumns(20);
        Text_area.setRows(5);
        jScrollPane2.setViewportView(Text_area);

        Ord_txt.setText("Escoja el método de ordenamiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(num_carros_text)
                        .addGap(18, 18, 18)
                        .addComponent(numero_carros, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Marca_text)
                                .addGap(52, 52, 52)
                                .addComponent(Modelo_text)
                                .addGap(55, 55, 55)
                                .addComponent(Color_text))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kilometraje_text)
                                    .addComponent(Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Ordenamiento_km)
                                        .addGap(12, 12, 12)
                                        .addComponent(Submit_Atributos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Ordenamiento_md, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(Submit_cant, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Ord_txt)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Ord_txt)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero_carros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_carros_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Submit_cant)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelo_text)
                    .addComponent(Marca_text)
                    .addComponent(Color_text)
                    .addComponent(Kilometraje_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit_Atributos)
                    .addComponent(Ordenamiento_km)
                    .addComponent(Ordenamiento_md))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero_carrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_carrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_carrosActionPerformed

    private void Submit_cantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_cantActionPerformed
        this.num_carros = Integer.parseInt(this.numero_carros.getText());
        aux = num_carros;
        this.num_carros_text.setText("# carros:              " + num_carros);
        Submit_cant.setVisible(false);
        this.numero_carros.setVisible(false);
        Color.setVisible(true);
        Marca.setVisible(true);
        Kilometraje.setVisible(true);
        Modelo.setVisible(true);
        Color_text.setVisible(true);
        Marca_text.setVisible(true);
        Kilometraje_text.setVisible(true);
        Modelo_text.setVisible(true);
        Submit_Atributos.setVisible(true);
    }//GEN-LAST:event_Submit_cantActionPerformed

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaActionPerformed

    private void ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloActionPerformed

    private void KilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KilometrajeActionPerformed

    private void Submit_AtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_AtributosActionPerformed
        //Clase_Carros array_carros[] = new Clase_Carros[num_carros];
        
        num_carros--;
        array_carros[num_carros ] = new Clase_Carros(this.Modelo.getText(),this.Kilometraje.getText(),this.Marca.getText(),this.Color.getText());
        
        this.num_carros_text.setText("# carros:              " + num_carros);
        this.Modelo.setText("");
        this.Kilometraje.setText("");
        this.Marca.setText("");
        this.Color.setText("");
        if(num_carros == 0){
            Color.setVisible(false);
            Marca.setVisible(false);
            Kilometraje.setVisible(false);
            Modelo.setVisible(false);
            Color_text.setVisible(false);
            Marca_text.setVisible(false);
            Kilometraje_text.setVisible(false);
            Modelo_text.setVisible(false);
            Submit_Atributos.setVisible(false);
            if (ordenamiento == "md")
                this.num_carros_text.setText("   Carros ordenados por Modelo :");
            else
                this.num_carros_text.setText("   Carros ordenados por  Kilometraje:");
            Text_area.setVisible(true);
            Ord_txt.setVisible(false);
            for(int c = 0; c < aux; c++){ //intento de ordenamiento
                for(int x = 0; x < (aux - 1); x++){
                    if(array_carros[x].int_modelo() > array_carros[x+1].int_modelo()){
                    orden[x] = c+1;
                    orden[x+1] = c; 
                    }
                }
            }
            for(int c = 0; c < (aux); c++){               
                this.Text_area.setText(this.Text_area.getText() + array_carros[c].mostrar_datos());
            }
        }
               
    }//GEN-LAST:event_Submit_AtributosActionPerformed

    private void Ordenamiento_kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ordenamiento_kmActionPerformed
        Ordenamiento_km.setVisible(false);
        Ordenamiento_md.setVisible(false);
        Submit_cant.setVisible(true);
        numero_carros.setVisible(true);
        num_carros_text.setVisible(true);
        Ord_txt.setVisible(false);
        ordenamiento = "km";
    }//GEN-LAST:event_Ordenamiento_kmActionPerformed

    private void Ordenamiento_mdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ordenamiento_mdActionPerformed
        Ordenamiento_km.setVisible(false);
        Ordenamiento_md.setVisible(false);
        Submit_cant.setVisible(true);
        numero_carros.setVisible(true);
        num_carros_text.setVisible(true);
        Ord_txt.setVisible(false);
        ordenamiento = "md";
    }//GEN-LAST:event_Ordenamiento_mdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Color;
    private javax.swing.JLabel Color_text;
    private javax.swing.JTextField Kilometraje;
    private javax.swing.JLabel Kilometraje_text;
    private javax.swing.JTextField Marca;
    private javax.swing.JLabel Marca_text;
    private javax.swing.JTextField Modelo;
    private javax.swing.JLabel Modelo_text;
    private javax.swing.JLabel Ord_txt;
    private javax.swing.JButton Ordenamiento_km;
    private javax.swing.JButton Ordenamiento_md;
    private javax.swing.JButton Submit_Atributos;
    private javax.swing.JButton Submit_cant;
    private javax.swing.JTextArea Text_area;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel num_carros_text;
    private javax.swing.JTextField numero_carros;
    // End of variables declaration//GEN-END:variables
}
